# Generated by Django 3.2.25 on 2025-07-31 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('next_password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter 10 digit only : ')])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter your Address : ')])),
            ],
        ),
    ]
