# Generated by Django 3.2.25 on 2025-08-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
