# Generated by Django 3.2.25 on 2025-08-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('process', 'process'), ('complete', 'complete')], default='pending', max_length=20)),
                ('project_manager', models.ForeignKey(limit_choices_to={'role': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, to='task_manager.login')),
            ],
        ),
    ]
