# Generated by Django 3.2.25 on 2025-08-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('std', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VII', 'VII'), ('XI', 'XI'), ('X', 'X')], default='I', max_length=5)),
                ('science', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('english', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
