# Generated by Django 3.2.25 on 2025-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('re_password', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('Teacher', models.BooleanField()),
                ('Principle', models.BooleanField()),
            ],
        ),
    ]
